language: python

python:
  - 3.9.7
install:
  - pip install -r requirements.txt

script:
  - coverage run --omit 'virtualenv/*' -m unittest discover 
  - coverage report


after_success:
  - coveralls 
