"""Initial migration.

Revision ID: 1a37101df3a7
Revises: 
Create Date: 2021-12-06 17:11:12.213712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a37101df3a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_db', sa.Column('organisation3', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department_db', 'organisation3')
    # ### end Alembic commands ###
