"""Initial migration.

Revision ID: b3c5df7f2ea7
Revises: 1a37101df3a7
Create Date: 2021-12-06 17:13:34.573338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c5df7f2ea7'
down_revision = '1a37101df3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department_db', 'organisation3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_db', sa.Column('organisation3', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
